In [ ]:
!pip install keras 


In [ ]:
import numpy as np

import pandas as pd



df = pd.read_csv("Train_data1.csv")

In [ ]:
df.head()

Label     Time                        Data  Sentiment
0      0  10.35pm          she is a good girl          1
1      1  11.01am                I Love Music          1
2      2  03.12pm              she hates milk          0
3      3  06.06pm         Iam a good Listener          1
4      4  12.03am  I Love Harry Potter series          1

In [ ]:
df.tail()

Label     Time                                      Data  Sentiment
26     26  10.45pm  swarna is the prettiest girl in th class          1
27     27  11.30am                           NO ONE LOVES ME          0
28     28   3.45pm                         Iam a good dancer          1
29     29  11.13pm                    she is good at English          1
30     30  12.37am                  he loves to play cricket          1

In [ ]:
df["Data"]

0                            she is a good girl
1                                  I Love Music
2                                she hates milk
3                           Iam a good Listener
4                    I Love Harry Potter series
5                 She is so exhausted with them
6                   Maharshi movie is excellent
7              Cleanliness is next to Godliness
8     Mahatma Gandhi is a great freedom figther
9                        Latha loves Lofi music
10    They were so sad after listening the news
11                              Rama loves Sita
12                                Love Yourself
13          Well done is better than well said.
14             Cherish the Good moments in Life
15             Everyone goes thorugh Depression
16                     Iam HAPPY at this moment
17                             Blissful moments
18                        Pleasure meeting you.
19                     I faced lot of problems.
20                   my sister is a good

In [ ]:
df=df.dropna()

In [ ]:
##get independent features

X=df.drop("Sentiment",axis=1)

In [ ]:
##get dependent features

y=df["Sentiment"]

In [ ]:
X.shape

(31, 3)

In [ ]:
y.shape

(31,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.5.0'

In [ ]:
from tensorflow.keras.layers import Embedding

from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential

from tensorflow.keras.preprocessing.text import one_hot

from tensorflow.keras.layers import LSTM

from tensorflow.keras.layers import Dense


In [ ]:
### vocabulary size
voc_size=5000


**One hot representation**

In [ ]:
messages=X.copy()

In [ ]:
messages

Label     Time                                       Data
0       0  10.35pm                         she is a good girl
1       1  11.01am                               I Love Music
2       2  03.12pm                             she hates milk
3       3  06.06pm                        Iam a good Listener
4       4  12.03am                 I Love Harry Potter series
5       5  11.11pm              She is so exhausted with them
6       6  12.06am                Maharshi movie is excellent
7       7  07.00am           Cleanliness is next to Godliness
8       8  09.15pm  Mahatma Gandhi is a great freedom figther
9       9  12.34am                     Latha loves Lofi music
10     10  06.09am  They were so sad after listening the news
11     11  05.30am                            Rama loves Sita
12     12   6.15pm                              Love Yourself
13     13   2.00am        Well done is better than well said.
14     14   3.30pm           Cherish the Good moments in Life
15     15  12.24pm           Everyone goes thorugh Depression
16     16   1.15pm                   Iam HAPPY at this moment
17     17   8.16am                           Blissful moments
18     18   9.45pm                      Pleasure meeting you.
19     19  10.45am                   I faced lot of problems.
20     20   2.50pm                 my sister is a good singer
21     21   4.55pm     AR Rahman is one of the finest Artist.
22     22   5.30am                      Happy Birthday to you
23     23   7.45am              THIS is a bad day in my life.
24     24   8.55pm                             I hate my life
25     25   9.30am                        she looks beautiful
26     26  10.45pm   swarna is the prettiest girl in th class
27     27  11.30am                            NO ONE LOVES ME
28     28   3.45pm                          Iam a good dancer
29     29  11.13pm                     she is good at English
30     30  12.37am                   he loves to play cricket

In [ ]:
messages.get('Data')

0                            she is a good girl
1                                  I Love Music
2                                she hates milk
3                           Iam a good Listener
4                    I Love Harry Potter series
5                 She is so exhausted with them
6                   Maharshi movie is excellent
7              Cleanliness is next to Godliness
8     Mahatma Gandhi is a great freedom figther
9                        Latha loves Lofi music
10    They were so sad after listening the news
11                              Rama loves Sita
12                                Love Yourself
13          Well done is better than well said.
14             Cherish the Good moments in Life
15             Everyone goes thorugh Depression
16                     Iam HAPPY at this moment
17                             Blissful moments
18                        Pleasure meeting you.
19                     I faced lot of problems.
20                   my sister is a good

In [ ]:
messages.loc[3]

Label                      3
Time                 06.06pm
Data     Iam a good Listener
Name: 3, dtype: object

In [ ]:
messages['Data'][1]

'I Love Music'

In [ ]:
##messages.reset_index(inplace=True)

In [ ]:
messages.head()

Label     Time                        Data
0      0  10.35pm          she is a good girl
1      1  11.01am                I Love Music
2      2  03.12pm              she hates milk
3      3  06.06pm         Iam a good Listener
4      4  12.03am  I Love Harry Potter series

In [ ]:
messages.iloc[:,0]

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
26    26
27    27
28    28
29    29
30    30
Name: Label, dtype: int64

In [ ]:
messages.iloc[:,1]

0     10.35pm
1     11.01am
2     03.12pm
3     06.06pm
4     12.03am
5     11.11pm
6     12.06am
7     07.00am
8     09.15pm
9     12.34am
10    06.09am
11    05.30am
12     6.15pm
13     2.00am
14     3.30pm
15    12.24pm
16     1.15pm
17     8.16am
18     9.45pm
19    10.45am
20     2.50pm
21     4.55pm
22     5.30am
23     7.45am
24     8.55pm
25     9.30am
26    10.45pm
27    11.30am
28     3.45pm
29    11.13pm
30    12.37am
Name: Time, dtype: object

In [ ]:
import nltk
## re -- regular expression
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
stop_words = {"i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself",
              "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself",
              "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that", "these",
              "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "having", "do",
              "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because", "as", "until", "while",
              "of", "at", "by", "for", "with", "about", "against", "between", "into", "through", "during", "before",
              "after", "above", "below", "to", "from", "up", "down", "in", "out", "on", "off", "over", "under", "again",
              "further", "then", "once", "here", "there", "when", "where", "why", "how", "all", "any", "both", "each",
              "few", "more", "most", "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so", "than",
              "too", "very", "s", "t", "can", "will", "just", "don", "should", "now"'a','of','only','for','an','they','to','let','me', 'aboard','about','above','across','after','against','along',
'amid','among','anti','around','as','at','before','behind','below','beneath','beside','besides','between','beyond','but','by',
'concerning','considering','despite','down','during','except','excepting','excluding','following','for','from','in','inside',
'into','like','minus','near','of','off','on','onto','opposite','outside','over','past','per','plus','regarding','round','save',
'since','than','through','to','toward','towards','under','underneath','unlike','until','up','upon','versus','via','with','within','without','the'}

In [ ]:
###Data preprocessing
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0,len(messages)):
  print(i)
  review= re.sub('[^a-zA-Z]',' ',messages["Data"][i])
  review= review.lower()
  review= review.split()

  review= [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30


In [ ]:
corpus

['good girl',
 'love music',
 'hate milk',
 'iam good listen',
 'love harri potter seri',
 'exhaust',
 'maharshi movi excel',
 'cleanli next godli',
 'mahatma gandhi great freedom figther',
 'latha love lofi music',
 'sad listen news',
 'rama love sita',
 'love',
 'well done better well said',
 'cherish good moment life',
 'everyon goe thorugh depress',
 'iam happi moment',
 'bliss moment',
 'pleasur meet',
 'face lot problem',
 'sister good singer',
 'ar rahman one finest artist',
 'happi birthday',
 'bad day life',
 'hate life',
 'look beauti',
 'swarna prettiest girl th class',
 'one love',
 'iam good dancer',
 'good english',
 'love play cricket']

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[1530, 3020],
 [4582, 1801],
 [2916, 1424],
 [1340, 1530, 3241],
 [4582, 2165, 921, 851],
 [2635],
 [511, 4115, 3804],
 [431, 1390, 4725],
 [2746, 2250, 1249, 3589, 4493],
 [959, 4582, 1129, 1801],
 [2895, 3241, 1376],
 [4183, 4582, 4610],
 [4582],
 [2658, 149, 2963, 2658, 1962],
 [1432, 1530, 714, 2799],
 [2375, 4969, 1521, 4749],
 [1340, 2023, 714],
 [2572, 714],
 [1617, 2025],
 [1334, 2389, 1642],
 [625, 1530, 3728],
 [4307, 1267, 2871, 3813, 2261],
 [2023, 466],
 [2491, 2265, 2799],
 [2916, 2799],
 [1870, 2167],
 [532, 2112, 3020, 4994, 2849],
 [2871, 4582],
 [1340, 1530, 2007],
 [1530, 2769],
 [4582, 2396, 4155]]

**Emmbedding Representation**

In [ ]:
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    0    0    0    0 1530 3020]
 [   0    0    0    0    0    0    0    0 4582 1801]
 [   0    0    0    0    0    0    0    0 2916 1424]
 [   0    0    0    0    0    0    0 1340 1530 3241]
 [   0    0    0    0    0    0 4582 2165  921  851]
 [   0    0    0    0    0    0    0    0    0 2635]
 [   0    0    0    0    0    0    0  511 4115 3804]
 [   0    0    0    0    0    0    0  431 1390 4725]
 [   0    0    0    0    0 2746 2250 1249 3589 4493]
 [   0    0    0    0    0    0  959 4582 1129 1801]
 [   0    0    0    0    0    0    0 2895 3241 1376]
 [   0    0    0    0    0    0    0 4183 4582 4610]
 [   0    0    0    0    0    0    0    0    0 4582]
 [   0    0    0    0    0 2658  149 2963 2658 1962]
 [   0    0    0    0    0    0 1432 1530  714 2799]
 [   0    0    0    0    0    0 2375 4969 1521 4749]
 [   0    0    0    0    0    0    0 1340 2023  714]
 [   0    0    0    0    0    0    0    0 2572  714]
 [   0    0    0    0    0    0    0    0 1617

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0, 1530, 3020],
      dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 10, 40)            200000    
_________________________________________________________________
lstm_3 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(31, (31,))

In [ ]:
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((31, 10), (31,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

**Model Training**

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
1/1 [==============================] - 0s 66ms/step - loss: 0.4841 - accuracy: 0.8000 - val_loss: 0.7654 - val_accuracy: 0.6364
Epoch 2/10
1/1 [==============================] - 0s 31ms/step - loss: 0.4730 - accuracy: 0.8000 - val_loss: 0.7369 - val_accuracy: 0.6364
Epoch 3/10
1/1 [==============================] - 0s 37ms/step - loss: 0.4656 - accuracy: 0.8000 - val_loss: 0.7153 - val_accuracy: 0.6364
Epoch 4/10
1/1 [==============================] - 0s 37ms/step - loss: 0.4615 - accuracy: 0.8000 - val_loss: 0.7003 - val_accuracy: 0.6364
Epoch 5/10
1/1 [==============================] - 0s 42ms/step - loss: 0.4593 - accuracy: 0.8000 - val_loss: 0.6904 - val_accuracy: 0.6364
Epoch 6/10
1/1 [==============================] - 0s 35ms/step - loss: 0.4575 - accuracy: 0.8000 - val_loss: 0.6844 - val_accuracy: 0.6364
Epoch 7/10
1/1 [==============================] - 0s 40ms/step - loss: 0.4553 - accuracy: 0.8000 - val_loss: 0.6812 - val_accuracy: 0.6364
Epoch 8/10
1/1 [===========

**Adding Dropout**

In [ ]:
from tensorflow.keras.layers import Dropout

## Creating model
embedding_vector_features=40

model=Sequential()

model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))

model.add(Dropout(0.3))

model.add(LSTM(100))

model.add(Dropout(0.3))

model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

**performance metrics and accuracy**

In [ ]:
y_pred=model.predict_classes(X_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[2, 2],
       [4, 3]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.45454545454545453

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.33      0.50      0.40         4
           1       0.60      0.43      0.50         7

    accuracy                           0.45        11
   macro avg       0.47      0.46      0.45        11
weighted avg       0.50      0.45      0.46        11

