In [ ]:
!pip install keras 
!sudo pip install h5py

In [ ]:
import numpy as np

import pandas as pd

import os

df = pd.read_csv("Data_status.csv")

In [ ]:
df.head()

Label     Time                        Data  Sentiment
0      0  10.35pm          she is a good girl          1
1      1  11.01am                I Love Music          1
2      2  03.12pm              she hates milk          0
3      3  06.06pm         Iam a good Listener          1
4      4  12.03am  I Love Harry Potter series          1

In [ ]:
df['Sentiment'].value_counts()


1    107
0    104
Name: Sentiment, dtype: int64

In [ ]:
df["Data"]

0                               she is a good girl
1                                     I Love Music
2                                   she hates milk
3                              Iam a good Listener
4                       I Love Harry Potter series
                          ...                     
206                Telling lies is very bad thing.
207         People are losing humanity day by day.
208           The owner tortured the child rudely.
209     My friend fell down and was injured badly.
210    It is hear-breaking to lose our loved ones.
Name: Data, Length: 211, dtype: object

In [ ]:
##dropping Nan values
df=df.dropna()

In [ ]:
df["Data"]

0                               she is a good girl
1                                     I Love Music
2                                   she hates milk
3                              Iam a good Listener
4                       I Love Harry Potter series
                          ...                     
206                Telling lies is very bad thing.
207         People are losing humanity day by day.
208           The owner tortured the child rudely.
209     My friend fell down and was injured badly.
210    It is hear-breaking to lose our loved ones.
Name: Data, Length: 211, dtype: object

**Feature extraction**

In [ ]:
##get independent features

X=df.drop("Sentiment",axis=1)

In [ ]:
##get dependent features

y=df["Sentiment"]

In [ ]:
X.shape

(211, 3)

In [ ]:
y.shape

(211,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.5.0'

In [ ]:
### vocabulary size
voc_size=5000


In [ ]:
##copying X data into messages
messages=X.copy()

In [ ]:
messages

Label     Time                                         Data
0        0  10.35pm                           she is a good girl
1        1  11.01am                                 I Love Music
2        2  03.12pm                               she hates milk
3        3  06.06pm                          Iam a good Listener
4        4  12.03am                   I Love Harry Potter series
..     ...      ...                                          ...
206    206  12.30am              Telling lies is very bad thing.
207    207   3.40pm       People are losing humanity day by day.
208    208  11.36am         The owner tortured the child rudely.
209    209   7.45am   My friend fell down and was injured badly.
210    210   8.55pm  It is hear-breaking to lose our loved ones.

[211 rows x 3 columns]

In [ ]:
messages.get('Data')

0                               she is a good girl
1                                     I Love Music
2                                   she hates milk
3                              Iam a good Listener
4                       I Love Harry Potter series
                          ...                     
206                Telling lies is very bad thing.
207         People are losing humanity day by day.
208           The owner tortured the child rudely.
209     My friend fell down and was injured badly.
210    It is hear-breaking to lose our loved ones.
Name: Data, Length: 211, dtype: object

In [ ]:
messages.loc[3]

Label                      3
Time                 06.06pm
Data     Iam a good Listener
Name: 3, dtype: object

In [ ]:
messages['Data'][1]

'I Love Music'

In [ ]:
##messages.reset_index(inplace=True)

In [ ]:
messages.head()

Label     Time                        Data
0      0  10.35pm          she is a good girl
1      1  11.01am                I Love Music
2      2  03.12pm              she hates milk
3      3  06.06pm         Iam a good Listener
4      4  12.03am  I Love Harry Potter series

In [ ]:
messages.iloc[:,1]

0      10.35pm
1      11.01am
2      03.12pm
3      06.06pm
4      12.03am
        ...   
206    12.30am
207     3.40pm
208    11.36am
209     7.45am
210     8.55pm
Name: Time, Length: 211, dtype: object

In [ ]:
import nltk
## re -- regular expression
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
###Data preprocessing
#from nltk.stem.porter import PorterStemmer
#ps=PorterStemmer()
corpus=[]
for i in range(0,len(messages)):
  print(i)
  review= re.sub('[^a-zA-Z0-9]',' ',messages["Data"][i])
  review= review.lower()
  #review= review.split()

  #review= [ps.stem(word) for word in review if not word in stopwords.words('english')]
  #review=' '.join(review)
  corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210


In [ ]:
corpus

['she is a good girl',
 'i love music',
 'she hates milk',
 'iam a good listener',
 'i love harry potter series',
 'she is so exhausted with them',
 'maharshi movie is excellent',
 'cleanliness is next to godliness',
 'mahatma gandhi is a great freedom figther',
 'latha loves lofi music',
 'they were so sad after listening the news',
 'rama loves sita',
 'love yourself',
 'well done is better than well said ',
 'cherish the good moments in life',
 'everyone goes thorugh depression',
 'iam happy at this moment',
 'blissful moments',
 'pleasure meeting you ',
 'i faced lot of problems ',
 'my sister is a good singer',
 'ar rahman is one of the finest artist ',
 'happy birthday to you',
 'this is a bad day in my life ',
 'i hate my life',
 'she looks beautiful',
 'swarna is the prettiest girl in th class',
 'no one loves me',
 'iam a good dancer',
 'she is good at english',
 'he loves to play cricket',
 'johnny enjoys watching cartoons',
 'hema cheated raju so they broke up ',
 'raju ador

In [ ]:
from tensorflow.keras.layers import Embedding

from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential

from tensorflow.keras.preprocessing.text import one_hot

from tensorflow.keras.layers import LSTM

from tensorflow.keras.layers import Dense

from tensorflow.keras.layers import Dropout

from keras.models import model_from_json


In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[759, 2389, 4567, 745, 4832],
 [58, 3270, 3770],
 [759, 3306, 2216],
 [2990, 4567, 745, 2427],
 [58, 3270, 3728, 1130, 3868],
 [759, 2389, 4299, 2117, 3071, 3948],
 [2418, 2944, 2389, 4306],
 [1804, 2389, 874, 4474, 4011],
 [465, 2829, 2389, 4567, 3330, 1750, 3877],
 [1657, 354, 4374, 3770],
 [3951, 1167, 4299, 4592, 4511, 2320, 3837, 3904],
 [3196, 354, 2731],
 [3270, 2446],
 [1256, 1208, 2389, 2947, 148, 1256, 2604],
 [3638, 3837, 745, 1053, 404, 3419],
 [1962, 481, 2607, 397],
 [2990, 144, 4938, 4789, 3896],
 [298, 1053],
 [360, 1830, 4756],
 [58, 926, 3677, 2969, 2488],
 [3272, 292, 2389, 4567, 745, 4354],
 [2171, 288, 2389, 4588, 2969, 3837, 1755, 1682],
 [144, 539, 4474, 4756],
 [4789, 2389, 4567, 2559, 4058, 404, 3272, 3419],
 [58, 1528, 3272, 3419],
 [759, 352, 4729],
 [3380, 2389, 3837, 3745, 4832, 404, 4348, 4716],
 [1497, 4588, 354, 3033],
 [2990, 4567, 745, 3909],
 [759, 2389, 745, 4938, 4940],
 [3727, 354, 4474, 1995, 3113],
 [3724, 3745, 3913, 2530],
 [121, 3842, 1425, 4

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4567  745 4832]
 [   0    0    0 ...   58 3270 3770]
 [   0    0    0 ...  759 3306 2216]
 ...
 [   0    0    0 ... 3837 1197 1985]
 [   0    0    0 ... 1447 1224  333]
 [   0    0    0 ... 3017 2718  708]]


In [ ]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,   58, 3270, 3770], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40

model=Sequential()

model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))

model.add(Dropout(0.3))

model.add(LSTM(100))

model.add(Dropout(0.3))

model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
dropout (Dropout)            (None, 20, 40)            0         
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs)

211

In [ ]:
y.shape

(211,)

In [ ]:
y

0      1
1      1
2      0
3      1
4      1
      ..
206    0
207    0
208    0
209    0
210    0
Name: Sentiment, Length: 211, dtype: int64

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((211, 20), (211,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
## Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
3/3 [==============================] - 7s 264ms/step - loss: 0.6935 - accuracy: 0.5248 - val_loss: 0.6954 - val_accuracy: 0.4286
Epoch 2/10
3/3 [==============================] - 0s 28ms/step - loss: 0.6902 - accuracy: 0.5461 - val_loss: 0.6952 - val_accuracy: 0.4286
Epoch 3/10
3/3 [==============================] - 0s 27ms/step - loss: 0.6879 - accuracy: 0.5461 - val_loss: 0.6963 - val_accuracy: 0.4286
Epoch 4/10
3/3 [==============================] - 0s 24ms/step - loss: 0.6859 - accuracy: 0.5461 - val_loss: 0.6987 - val_accuracy: 0.4286
Epoch 5/10
3/3 [==============================] - 0s 24ms/step - loss: 0.6807 - accuracy: 0.5461 - val_loss: 0.7045 - val_accuracy: 0.4286
Epoch 6/10
3/3 [==============================] - 0s 24ms/step - loss: 0.6746 - accuracy: 0.5461 - val_loss: 0.7194 - val_accuracy: 0.4286
Epoch 7/10
3/3 [==============================] - 0s 23ms/step - loss: 0.6700 - accuracy: 0.5461 - val_loss: 0.7358 - val_accuracy: 0.4286
Epoch 8/10
3/3 [==========

In [ ]:
score,acc = model.evaluate(X_test, y_test, verbose = 2, batch_size = 64)
print("score: %.2f" % (score))
print("acc: %.2f" % (acc))

2/2 - 0s - loss: 0.6856 - accuracy: 0.5286
score: 0.69
acc: 0.53


In [ ]:
model.save('model.h5')
print("Saved model to disk")

Saved model to disk


In [ ]:
from keras.models import load_model
model=load_model('model.h5')
print("model loaded")

model loaded


In [ ]:
y_pred=model.predict_classes(X_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[ 8, 32],
       [ 0, 30]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5428571428571428

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.20      0.33        40
           1       0.48      1.00      0.65        30

    accuracy                           0.54        70
   macro avg       0.74      0.60      0.49        70
weighted avg       0.78      0.54      0.47        70



In [ ]:
y = pd.get_dummies(df['Sentiment']).values
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.33, random_state = 42)
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(141, 3) (141, 2)
(70, 3) (70, 2)


In [ ]:
pos_cnt, neg_cnt, pos_correct, neg_correct = 0, 0, 0, 0
for x in range(len(X_test)):
    
    result = model.predict_classes(X_test)
   
    if np.argmax(result) == np.argmax(y_test[x]):
        if np.argmax(y_test[x]) == 0:
            neg_correct += 1
        else:
            pos_correct += 1
       
    if np.argmax(y_test[x]) == 0:
        neg_cnt += 1
    else:
        pos_cnt += 1



print("pos_acc", pos_correct/pos_cnt*100, "%")
print("neg_acc", neg_correct/neg_cnt*100, "%")

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


ValueError: ignored

In [ ]:
!sudo apt install tesseract-ocr
!pip install pytesseract